language: objective-c
osx_image: xcode8
before_install:
  - brew tap theseal/ssh-askpass
  - brew install ssh-askpass
  - sudo ln -s /usr/local/bin/ssh-askpass /usr/X11R6/bin/ssh-askpass
  - swift package generate-xcodeproj
script:
  - swift test
notifications:
  slack: ushios:wLQKkRtDpNIRkG4wuretSQqq
